### ISSUE TITLE
Bug in instrumentation

### ISSUE THREAD

**Issue by tnkhanh** [sbip-sg/discover#41]
I figured what caused the bug.
The function
```c++ 
__assert_bug_integer_overflow(void* [..])
```
has IR of form 
```llvm
@__assert_bug_integer_overflow_i32(i8* %arg105[..] )
```
Instructions usually have IRs of type `i32` or `i64` and that doesnt match `i8*`

**Comment by taquangtrung** [comment]
@tnkhanh: can you print the output IR here?

**Comment by tnkhanh** [comment]
For example, this is the assert function
```llvm
; Function Attrs: noinline nounwind uwtable
define dso_local void @__assert_bug_integer_overflow(i8* %0, i32 %1) #0 !dbg !175 {
  %3 = alloca i8*, align 8
  %4 = alloca i32, align 4
  store i8* %0, i8** %3, align 8
  call void @llvm.dbg.declare(metadata i8** %3, metadata !178, metadata !DIExpression()), !dbg !179
  store i32 %1, i32* %4, align 4
  call void @llvm.dbg.declare(metadata i32* %4, metadata !180, metadata !DIExpression()), !dbg !181
  ret void, !dbg !182
}
```

**Comment by tnkhanh** [comment]
From working bitcode, I inserted this call, and it causes the error `'@__assert_bug_integer_overflow' defined with type 'void (i8*, i32)*' but expected 'void (i32, i32)*'`
```llvm
  call void @__assert_bug_integer_overflow(i32 %14, i32 32), !dbg !212
```

**Comment by taquangtrung** [comment]
I see. Here are my suggestions:

- In `call void @__assert_bug_integer_overflow(i32 %14, i32 32)`, remove the bitwidth `i32 32` since it is already indicated by the first argument `i32 %14`.

- Generate the declaration of the assertion `__assert_bug_integer_overflow_i32` on the fly:
  + Don't declare it in the header file `discover.h`
  + Only declare it during the instrumentation of bug annotations.
  + Don't define the assertion's body, as the assertion is only used internally by Discover.

**Comment by tnkhanh** [comment]
I think it is okay to have the function defined in the header like we have now.  I have an idea that we can over load it with
``` C++
__assert_bug_integer_overflow(int);
__assert_bug_integer_overflow(long);
```

**Comment by taquangtrung** [comment]
There could be many types of integer bitwidth like i1, i2, i8, ... i256, so need to think of a general solution.

LLVM typing is strict: it doesn't support overloading.

My suggestion is to generate the declaration on the fly directly to the bitcode, so that we don't need to declare it in the header file.

You can also explore if C macros can be used, but I'm not sure if C macros can handle this case.

**Comment by tnkhanh** [comment]
I see. This seems reasonable. I will try generating the function and use it

**Comment by tnkhanh** [comment]
For now, I can generate the declarations. This is just declarations so clang won't compile.
```llvm
declare void @__assert_bug_integer_overflow_i16(i16)
```
Do we need to generate the definitions so it will compile?

**Comment by tnkhanh** [comment]
I'm working on making an empty function

**Comment by taquangtrung** [comment]
> For now, I can generate the declarations. This is just declarations so clang won't compile.
> 
> ```llvm
> declare void @__assert_bug_integer_overflow_i16(i16)
> ```
> 
> Do we need to generate the definitions so it will compile?

No, we don't need the function body.

This function will be handled by Discover internally. Need to make sure that it doesn't remove the function during normalization.

**Comment by tnkhanh** [comment]
Alright. I think this one is solved
